sudo: false
language: node_js
node_js:
  - '6.9.1'
  
install:
- npm install;

script:
- tsc -p ./;
- npm run test;

before_deploy:
- npm install -g vsce;
- vsce package;

after_failure: 
- "ls"
- "cat /home/travis/build/aaron-bond/better-comments/npm-debug.log"
