sudo: false
os: linux
language: node_js
node_js: '6.9.1'

before_install:
- export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
- sh -e /etc/init.d/xvfb start;

install:
- npm install
- npm run vscode:prepublish

script:
  - npm test --silent
  
after_failure:
- "cat /home/travis/build/aaron-bond/better-comments/npm-debug.log"
